### PR TITLE
fix duplicate cucumber run in host application

### LINKED ISSUE #398: Cucumber tests run twice
When you run cuke test (all features, a feature, scenario), it will run twice. Can be checked also in travis-ci.

### PR DESCRIPTION
**Pull request by martinpovolny**
closes https://github.com/aeolusproject/conductor/issues/398

### CODE REVIEW

**Comment by jguiditta** [comment]
Or we can just remove the file, we have no cukes anyway

**Comment by martinpovolny** [comment]
ok, will you remove the file or shall I change to the defined? call?

**Comment by martinpovolny** [comment]
changed to the defined? call

**Comment by jguiditta** [comment]
I don't see any reason to have a cucumber task anymore in Tim, as we dont use cucumber.  I had left it initially in case we wanted to bring it back, but if it is causing problems for a host app, then let's ditch it.  I just did so in pull #107 if you would like to verify that fixes the issue for you.

**Comment by jguiditta** [comment]
We decided to just ditch this file in pull #107, so closing this out

**Pull request closed without merging**
